name: Build and Deployment App

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: thmtthu1/itel-email-tasker
  APP_PATH: /home/minhthu/Intelligent-Email-Tasker-Backend
  COMPOSE_FILE: docker-compose-application.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      docker_image: ${{ steps.meta.outputs.full_image_name }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Generate Image Metadata
        id: meta
        shell: bash
        run: |
          set -e
          SHORT_SHA=$(git rev-parse --short HEAD)
          FULL_IMAGE="${DOCKERHUB_REPO}:${SHORT_SHA}"

          echo "SHORT_SHA=$SHORT_SHA"
          echo "FULL_IMAGE=$FULL_IMAGE"

          echo "full_image_name=$FULL_IMAGE" >> "$GITHUB_OUTPUT"

      - name: Debug meta output (same job)
        run: |
          echo "Meta output = '${{ steps.meta.outputs.full_image_name }}'"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ steps.meta.outputs.full_image_name }}

  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Generate Image Metadata
        id: meta
        shell: bash
        run: |
          set -e
          SHORT_SHA=$(git rev-parse --short HEAD)
          FULL_IMAGE="${DOCKERHUB_REPO}:${SHORT_SHA}"

          echo "SHORT_SHA=$SHORT_SHA"
          echo "FULL_IMAGE=$FULL_IMAGE"

          echo "full_image_name=$FULL_IMAGE" >> "$GITHUB_OUTPUT"

      - name: Update image in docker-compose
        run: |
          sed -i \
            "/^[[:space:]]*image:/c\    image: ${{ steps.meta.outputs.full_image_name }}" \
            ${{ secrets.APP_PATH }}/${{ secrets.COMPOSE_FILE }}

      - name: Show compose file (after replace)
        run: |
          cat ${{ secrets.APP_PATH }}/${{ secrets.COMPOSE_FILE }}

      - name: Pull images
        working-directory: ${{ secrets.APP_PATH }}
        run: |
          docker compose -f ${{ secrets.COMPOSE_FILE }} pull

      - name: Deploy
        working-directory: ${{ secrets.APP_PATH }}
        run: |
          docker compose -f ${{ secrets.COMPOSE_FILE }} up -d --no-deps

      - name: Show status
        working-directory: ${{ secrets.APP_PATH }}
        run: |
          docker compose ps
